CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" text NOT NULL,
        "FullName" character varying(100) NOT NULL,
        "Phone" character varying(15),
        "Address" character varying(500),
        "Avatar" character varying(500),
        "CreatedAt" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE TABLE "Categories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Slug" character varying(100) NOT NULL,
        "Description" character varying(500),
        "ImagePath" character varying(500),
        "SortOrder" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE TABLE "ShopConfigs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Key" character varying(100) NOT NULL,
        "Value" character varying(2000),
        "Type" character varying(20) NOT NULL,
        CONSTRAINT "PK_ShopConfigs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE TABLE "Carts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Carts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Carts_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE TABLE "Orders" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "OrderCode" character varying(20) NOT NULL,
        "FullName" character varying(100) NOT NULL,
        "Phone" character varying(15) NOT NULL,
        "Address" character varying(500) NOT NULL,
        "Note" character varying(500),
        "TotalAmount" numeric(18,0) NOT NULL,
        "Status" integer NOT NULL,
        "PaymentMethod" character varying(50) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Orders_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE TABLE "Products" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(200) NOT NULL,
        "Slug" character varying(200) NOT NULL,
        "Description" character varying(5000),
        "Price" numeric(18,0) NOT NULL,
        "OriginalPrice" numeric(18,0),
        "Brand" character varying(100),
        "Color" character varying(50),
        "Storage" character varying(50),
        "RAM" character varying(50),
        "ScreenSize" character varying(50),
        "CPU" character varying(100),
        "CategoryId" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "IsFeatured" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE TABLE "CartDetails" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CartId" integer NOT NULL,
        "ProductId" integer NOT NULL,
        "Quantity" integer NOT NULL,
        "UnitPrice" numeric(18,0) NOT NULL,
        CONSTRAINT "PK_CartDetails" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CartDetails_Carts_CartId" FOREIGN KEY ("CartId") REFERENCES "Carts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CartDetails_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE TABLE "OrderDetails" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" integer NOT NULL,
        "ProductId" integer NOT NULL,
        "ProductName" character varying(200) NOT NULL,
        "Quantity" integer NOT NULL,
        "UnitPrice" numeric(18,0) NOT NULL,
        CONSTRAINT "PK_OrderDetails" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OrderDetails_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_OrderDetails_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE TABLE "ProductImages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProductId" integer NOT NULL,
        "ImagePath" character varying(500) NOT NULL,
        "SortOrder" integer NOT NULL,
        "IsMain" boolean NOT NULL,
        CONSTRAINT "PK_ProductImages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProductImages_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    INSERT INTO "Categories" ("Id", "CreatedAt", "Description", "ImagePath", "IsActive", "Name", "Slug", "SortOrder")
    VALUES (1, TIMESTAMPTZ '2026-03-06T15:39:23.419972Z', 'Smartphone cao cap', NULL, TRUE, 'Dien thoai', 'dien-thoai', 1);
    INSERT INTO "Categories" ("Id", "CreatedAt", "Description", "ImagePath", "IsActive", "Name", "Slug", "SortOrder")
    VALUES (2, TIMESTAMPTZ '2026-03-06T15:39:23.419973Z', 'Laptop van phong va gaming', NULL, TRUE, 'Laptop', 'laptop', 2);
    INSERT INTO "Categories" ("Id", "CreatedAt", "Description", "ImagePath", "IsActive", "Name", "Slug", "SortOrder")
    VALUES (3, TIMESTAMPTZ '2026-03-06T15:39:23.419973Z', 'May tinh bang', NULL, TRUE, 'Tablet', 'tablet', 3);
    INSERT INTO "Categories" ("Id", "CreatedAt", "Description", "ImagePath", "IsActive", "Name", "Slug", "SortOrder")
    VALUES (4, TIMESTAMPTZ '2026-03-06T15:39:23.419973Z', 'Phu kien cong nghe', NULL, TRUE, 'Phu kien', 'phu-kien', 4);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    INSERT INTO "ShopConfigs" ("Id", "Key", "Type", "Value")
    VALUES (1, 'ShopName', 'string', 'Nexora');
    INSERT INTO "ShopConfigs" ("Id", "Key", "Type", "Value")
    VALUES (2, 'Phone', 'string', '0123456789');
    INSERT INTO "ShopConfigs" ("Id", "Key", "Type", "Value")
    VALUES (3, 'Email', 'string', 'contact@nexora.vn');
    INSERT INTO "ShopConfigs" ("Id", "Key", "Type", "Value")
    VALUES (4, 'Address', 'string', 'TP. Ho Chi Minh, Viet Nam');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE INDEX "IX_CartDetails_CartId" ON "CartDetails" ("CartId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE INDEX "IX_CartDetails_ProductId" ON "CartDetails" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Carts_UserId" ON "Carts" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Categories_Slug" ON "Categories" ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE INDEX "IX_OrderDetails_OrderId" ON "OrderDetails" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE INDEX "IX_OrderDetails_ProductId" ON "OrderDetails" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Orders_OrderCode" ON "Orders" ("OrderCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE INDEX "IX_Orders_UserId" ON "Orders" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE INDEX "IX_ProductImages_ProductId" ON "ProductImages" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Products_Slug" ON "Products" ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ShopConfigs_Key" ON "ShopConfigs" ("Key");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Categories"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Categories") + 1,
            nextval(pg_get_serial_sequence('"Categories"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"ShopConfigs"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "ShopConfigs") + 1,
            nextval(pg_get_serial_sequence('"ShopConfigs"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306153926_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260306153926_InitialCreate', '8.0.24');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307070103_AddVoucherAndOrderDiscount') THEN
    ALTER TABLE "Orders" ADD "DiscountAmount" numeric(18,0) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307070103_AddVoucherAndOrderDiscount') THEN
    ALTER TABLE "Orders" ADD "VoucherCode" character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307070103_AddVoucherAndOrderDiscount') THEN
    CREATE TABLE "Vouchers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(20) NOT NULL,
        "Description" character varying(200),
        "DiscountAmount" numeric(18,0) NOT NULL,
        "DiscountPercent" integer NOT NULL,
        "MinOrderAmount" numeric(18,0) NOT NULL,
        "MaxDiscountAmount" numeric(18,0) NOT NULL,
        "UsageLimit" integer NOT NULL,
        "UsedCount" integer NOT NULL,
        "StartDate" timestamp with time zone NOT NULL,
        "EndDate" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Vouchers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307070103_AddVoucherAndOrderDiscount') THEN
    UPDATE "Categories" SET "CreatedAt" = TIMESTAMPTZ '2026-03-07T07:01:02.318416Z'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307070103_AddVoucherAndOrderDiscount') THEN
    UPDATE "Categories" SET "CreatedAt" = TIMESTAMPTZ '2026-03-07T07:01:02.318417Z'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307070103_AddVoucherAndOrderDiscount') THEN
    UPDATE "Categories" SET "CreatedAt" = TIMESTAMPTZ '2026-03-07T07:01:02.318417Z'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307070103_AddVoucherAndOrderDiscount') THEN
    UPDATE "Categories" SET "CreatedAt" = TIMESTAMPTZ '2026-03-07T07:01:02.318417Z'
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307070103_AddVoucherAndOrderDiscount') THEN
    INSERT INTO "Vouchers" ("Id", "Code", "Description", "DiscountAmount", "DiscountPercent", "EndDate", "IsActive", "MaxDiscountAmount", "MinOrderAmount", "StartDate", "UsageLimit", "UsedCount")
    VALUES (1, 'WELCOME10', 'Giảm 10% cho đơn đầu tiên', 0.0, 10, TIMESTAMPTZ '2026-12-31T23:59:59Z', TRUE, 500000.0, 1000000.0, TIMESTAMPTZ '2026-01-01T00:00:00Z', 100, 0);
    INSERT INTO "Vouchers" ("Id", "Code", "Description", "DiscountAmount", "DiscountPercent", "EndDate", "IsActive", "MaxDiscountAmount", "MinOrderAmount", "StartDate", "UsageLimit", "UsedCount")
    VALUES (2, 'NEXORA50K', 'Giảm 50.000đ cho đơn từ 500K', 50000.0, 0, TIMESTAMPTZ '2026-12-31T23:59:59Z', TRUE, 0.0, 500000.0, TIMESTAMPTZ '2026-01-01T00:00:00Z', 200, 0);
    INSERT INTO "Vouchers" ("Id", "Code", "Description", "DiscountAmount", "DiscountPercent", "EndDate", "IsActive", "MaxDiscountAmount", "MinOrderAmount", "StartDate", "UsageLimit", "UsedCount")
    VALUES (3, 'FREESHIP', 'Giảm 30.000đ phí vận chuyển', 30000.0, 0, TIMESTAMPTZ '2026-12-31T23:59:59Z', TRUE, 0.0, 300000.0, TIMESTAMPTZ '2026-01-01T00:00:00Z', 500, 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307070103_AddVoucherAndOrderDiscount') THEN
    CREATE UNIQUE INDEX "IX_Vouchers_Code" ON "Vouchers" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307070103_AddVoucherAndOrderDiscount') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Vouchers"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Vouchers") + 1,
            nextval(pg_get_serial_sequence('"Vouchers"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307070103_AddVoucherAndOrderDiscount') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260307070103_AddVoucherAndOrderDiscount', '8.0.24');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307071505_UpdateSeedData') THEN
    UPDATE "Categories" SET "CreatedAt" = TIMESTAMPTZ '2026-03-07T07:15:04.444241Z', "Description" = 'Smartphone cao cấp từ các thương hiệu hàng đầu', "Name" = 'Điện thoại'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307071505_UpdateSeedData') THEN
    UPDATE "Categories" SET "CreatedAt" = TIMESTAMPTZ '2026-03-07T07:15:04.444242Z', "Description" = 'Laptop văn phòng, học tập và gaming'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307071505_UpdateSeedData') THEN
    UPDATE "Categories" SET "CreatedAt" = TIMESTAMPTZ '2026-03-07T07:15:04.444242Z', "Description" = 'Máy tính bảng đa năng'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307071505_UpdateSeedData') THEN
    UPDATE "Categories" SET "CreatedAt" = TIMESTAMPTZ '2026-03-07T07:15:04.444243Z', "Description" = 'Phụ kiện công nghệ: sạc, cáp, loa, tai nghe,...', "Name" = 'Phụ kiện'
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307071505_UpdateSeedData') THEN
    INSERT INTO "Categories" ("Id", "CreatedAt", "Description", "ImagePath", "IsActive", "Name", "Slug", "SortOrder")
    VALUES (5, TIMESTAMPTZ '2026-03-07T07:15:04.444243Z', 'Smartwatch và thiết bị đeo thông minh', NULL, TRUE, 'Đồng hồ thông minh', 'dong-ho-thong-minh', 5);
    INSERT INTO "Categories" ("Id", "CreatedAt", "Description", "ImagePath", "IsActive", "Name", "Slug", "SortOrder")
    VALUES (6, TIMESTAMPTZ '2026-03-07T07:15:04.444243Z', 'Loa, tai nghe, thiết bị âm thanh chất lượng cao', NULL, TRUE, 'Âm thanh', 'am-thanh', 6);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307071505_UpdateSeedData') THEN
    UPDATE "ShopConfigs" SET "Value" = '1900 8888'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307071505_UpdateSeedData') THEN
    UPDATE "ShopConfigs" SET "Value" = '268 Lý Thường Kiệt, Q.10, TP. Hồ Chí Minh'
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307071505_UpdateSeedData') THEN
    INSERT INTO "ShopConfigs" ("Id", "Key", "Type", "Value")
    VALUES (5, 'Facebook', 'string', 'https://facebook.com/nexora.vn');
    INSERT INTO "ShopConfigs" ("Id", "Key", "Type", "Value")
    VALUES (6, 'WorkingHours', 'string', '08:00 - 21:00 (Thứ 2 - Chủ nhật)');
    INSERT INTO "ShopConfigs" ("Id", "Key", "Type", "Value")
    VALUES (7, 'AboutUs', 'text', 'Nexora - Hệ thống bán lẻ công nghệ hàng đầu Việt Nam. Cam kết sản phẩm chính hãng, giá tốt nhất, bảo hành uy tín.');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307071505_UpdateSeedData') THEN
    INSERT INTO "Vouchers" ("Id", "Code", "Description", "DiscountAmount", "DiscountPercent", "EndDate", "IsActive", "MaxDiscountAmount", "MinOrderAmount", "StartDate", "UsageLimit", "UsedCount")
    VALUES (4, 'TETAM2025', 'Giảm 15% mừng Tết Âm lịch 2025', 0.0, 15, TIMESTAMPTZ '2025-02-15T23:59:59Z', TRUE, 1000000.0, 2000000.0, TIMESTAMPTZ '2025-01-15T00:00:00Z', 50, 42);
    INSERT INTO "Vouchers" ("Id", "Code", "Description", "DiscountAmount", "DiscountPercent", "EndDate", "IsActive", "MaxDiscountAmount", "MinOrderAmount", "StartDate", "UsageLimit", "UsedCount")
    VALUES (5, 'FLASH100', 'Flash sale giảm 100K', 100000.0, 0, TIMESTAMPTZ '2026-12-31T23:59:59Z', TRUE, 0.0, 500000.0, TIMESTAMPTZ '2026-01-01T00:00:00Z', 10, 10);
    INSERT INTO "Vouchers" ("Id", "Code", "Description", "DiscountAmount", "DiscountPercent", "EndDate", "IsActive", "MaxDiscountAmount", "MinOrderAmount", "StartDate", "UsageLimit", "UsedCount")
    VALUES (6, 'BIGDEAL20', 'Giảm 20% cho đơn từ 20 triệu', 0.0, 20, TIMESTAMPTZ '2026-12-31T23:59:59Z', TRUE, 5000000.0, 20000000.0, TIMESTAMPTZ '2026-01-01T00:00:00Z', 20, 0);
    INSERT INTO "Vouchers" ("Id", "Code", "Description", "DiscountAmount", "DiscountPercent", "EndDate", "IsActive", "MaxDiscountAmount", "MinOrderAmount", "StartDate", "UsageLimit", "UsedCount")
    VALUES (7, 'GIFT20K', 'Tặng 20K cho mọi đơn hàng', 20000.0, 0, TIMESTAMPTZ '2026-12-31T23:59:59Z', TRUE, 0.0, 0.0, TIMESTAMPTZ '2026-01-01T00:00:00Z', 1000, 0);
    INSERT INTO "Vouchers" ("Id", "Code", "Description", "DiscountAmount", "DiscountPercent", "EndDate", "IsActive", "MaxDiscountAmount", "MinOrderAmount", "StartDate", "UsageLimit", "UsedCount")
    VALUES (8, 'DISABLED', 'Voucher đã bị vô hiệu hóa', 500000.0, 0, TIMESTAMPTZ '2026-12-31T23:59:59Z', FALSE, 0.0, 0.0, TIMESTAMPTZ '2026-01-01T00:00:00Z', 100, 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307071505_UpdateSeedData') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Categories"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Categories") + 1,
            nextval(pg_get_serial_sequence('"Categories"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"ShopConfigs"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "ShopConfigs") + 1,
            nextval(pg_get_serial_sequence('"ShopConfigs"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Vouchers"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Vouchers") + 1,
            nextval(pg_get_serial_sequence('"Vouchers"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260307071505_UpdateSeedData') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260307071505_UpdateSeedData', '8.0.24');
    END IF;
END $EF$;
COMMIT;

